// @generated by tools/update_perfmon_events.py; do not edit by hand.
// Source: https://github.com/intel/perfmon @ 6e3329d20457aad11d8cc323b85aa6a16b075918; license: BSD-3-Clause in vendor/intel-perfmon/LICENSE.
use super::{
    CounterRestriction, EventProvenance, EventRole, MapfileRow, PerfmonAttribution, PerfmonEvent,
    PerfmonProfile, PerfmonProfileId, PerfmonSource, PerfmonSourceKind, PerfmonUnit,
    ProgrammableCounter, RuntimeField, RuntimeFieldValue, SourceField,
};

pub const UPSTREAM_COMMIT: &str = "6e3329d20457aad11d8cc323b85aa6a16b075918";

pub const ATTRIBUTION: PerfmonAttribution = PerfmonAttribution {
    upstream_repository: "https://github.com/intel/perfmon",
    upstream_commit: "6e3329d20457aad11d8cc323b85aa6a16b075918",
    license: "BSD-3-Clause",
    license_path: "vendor/intel-perfmon/LICENSE",
};

const SOURCE_0_EVENT_NAMES: &[&str] = &[
    "UNC_IIO_DATA_REQ_OF_CPU.MEM_READ.ALL_PARTS",
    "UNC_IIO_DATA_REQ_OF_CPU.MEM_WRITE.ALL_PARTS",
    "UNC_UPI_TxL_FLITS.ALL_DATA",
    "UNC_UPI_RxL_FLITS.ALL_DATA",
];
const SOURCE_1_EVENT_NAMES: &[&str] = &[
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.PART0",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.PART1",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.PART2",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.PART3",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.PART4",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.PART5",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.PART6",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.PART7",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.PART0",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.PART1",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.PART2",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.PART3",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.PART4",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.PART5",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.PART6",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.PART7",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.PART0",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.PART1",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.PART2",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.PART3",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.PART4",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.PART5",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.PART6",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.PART7",
];
const SOURCE_2_EVENT_NAMES: &[&str] = &[
    "UNC_IIO_DATA_REQ_OF_CPU.MEM_READ.ALL_PARTS",
    "UNC_IIO_DATA_REQ_OF_CPU.MEM_WRITE.ALL_PARTS",
    "UNC_UPI_TxL_FLITS.ALL_DATA",
    "UNC_UPI_RxL_FLITS.ALL_DATA",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.ALL_PARTS",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.ALL_PARTS",
];
const SOURCE_3_EVENT_NAMES: &[&str] = &[
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.ALL_PARTS",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_READ.PART0",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_READ.PART1",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_READ.PART2",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_READ.PART3",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_READ.PART4",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_READ.PART5",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_READ.PART6",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_READ.PART7",
];
const SPR_SPR_UNC_IIO_DATA_REQ_OF_CPU_PEER_WRITE_ALL_PARTS_SOURCE_NAMES: &[&str] = &[
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.PART0",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.PART1",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.PART2",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.PART3",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.PART4",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.PART5",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.PART6",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.PART7",
];
const SPR_SPR_UNC_IIO_DATA_REQ_OF_CPU_PEER_WRITE_ALL_PARTS_SOURCE_HASHES: &[&str] = &[
    "fd4e7cfe368ccb0114ad17dc108b4526cb3eef0150f1ac731001129453187c9e",
    "83a911ba21d5342face8f995ca3ba16a2059eaccd448040c3483be35ae819f94",
    "dd79bd76bee9b807d1cf73527f951a6890ef5caf3751cd8062af5b420276cd0e",
    "20ab0af0335eb1e841163c9a479631689cf7642cec6fcb53057a3bbda2bfca7a",
    "f8e96c19ae057052f94245ea4df786a72d1bef319f76ff0875cdc82e8b1107fb",
    "d1639643b1120b62e6d90044d765bc327046a8502a1ddc5413268e1f0f36d517",
    "a7d9b166c21853c168e3be6f1aacb6ddc92121bee5f15286a47a38a607af6299",
    "1b7c69659f160f80c981cbd093129a251916bdfc40e6291e7015fdc97550e853",
];
const SPR_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_WRITE_ALL_PARTS_SOURCE_NAMES: &[&str] = &[
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.PART0",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.PART1",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.PART2",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.PART3",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.PART4",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.PART5",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.PART6",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.PART7",
];
const SPR_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_WRITE_ALL_PARTS_SOURCE_HASHES: &[&str] = &[
    "8a3f9a2e3a09acb6d602da77a004ecbd840191289903717713dae631dd804afb",
    "d01d79c4cd9d48977ea1aace19f08c8665235c3f76f71fbf5a071d8012727b6e",
    "0cb7dcc118c3252bb51bd1c3bcb31f507f247d03d9c128f98722c0ded988c154",
    "bc3d0d5f913acec79dff22cbf3e701ed47aa48ace2ece460d7625057da29e003",
    "e99135f3c3c79950ab7f7c5b821513b9848bbab8635d5b96a2b7f33f96fe8c78",
    "6b1b66c20afe240ea1d66b4a2eb98b1bb516fdf93d5cbacda7c29a1094c54399",
    "ff79112deb2d2ee6e400e9a22fc5b5ef6c8caaedf905c6226b75eabd1a36ab22",
    "e061e4c5a4b96edd3fd6689f20df4ed01910423a3fd25586f493ac09d2b43aa3",
];
const SPR_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_READ_ALL_PARTS_SOURCE_NAMES: &[&str] = &[
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.PART0",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.PART1",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.PART2",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.PART3",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.PART4",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.PART5",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.PART6",
    "UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.PART7",
];
const SPR_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_READ_ALL_PARTS_SOURCE_HASHES: &[&str] = &[
    "8be38144849a129dfbad0ed1ab52e92fddc9a2d354203701f1196089cf02fedb",
    "9e4304aff9114c0a47f945fa9154338dab25e74b848fa2a09c7f746c3f6360dc",
    "b93de4ce75d412fb7796545b3e3f668bf2546e99b6e0f25cf40926974c3833c7",
    "bbb25430c7eb010b2393d1c4f7d84b47e7393fa2fb0aa33617c7f3385d1f6337",
    "f636f9f099df97a63b68c6cbef7860c2f4096e56eb6be8087042b61579fe5929",
    "6bffe8741e358e0b83d39cbae9a990cda8869afe36d87fa95afbf59469c3bcb1",
    "9b6c71a6abd1bf83e016ea41fca272c9845c712a7db25835a7d76bf9cfe1f4e7",
    "fad422cfe7515982aeff10f4235ffdbc8914902e574afe7d9e01d482f5e1d51d",
];
const GNR_GNR_UNC_IIO_DATA_REQ_OF_CPU_PEER_READ_ALL_PARTS_SOURCE_NAMES: &[&str] = &[
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_READ.PART0",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_READ.PART1",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_READ.PART2",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_READ.PART3",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_READ.PART4",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_READ.PART5",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_READ.PART6",
    "UNC_IIO_DATA_REQ_OF_CPU.PEER_READ.PART7",
];
const GNR_GNR_UNC_IIO_DATA_REQ_OF_CPU_PEER_READ_ALL_PARTS_SOURCE_HASHES: &[&str] = &[
    "ecf029a523b24bc506dc0919e91ceefd8c40d8c3a96e2daa2848af9aed16ab7a",
    "86ea50424c23207c682a04418a524432c35451843dfe1e66984bdb1d990d8d47",
    "1bbfd1196c0b42f05be9712616fed92f1f3da2cbc88634afd404910596051822",
    "3257de5c55049e90ef7b6bdad5052ef8f481e9e8200a64c315f78fe40cba180a",
    "4ce6abab9a1902d6186a2f59b34467dcfa21ba191b0814e93f9ae18e15c87af7",
    "53fa6b29149970b25c0789a6869720915747a8783e7c594dd6a596f4623f12cf",
    "751ab15404391559b034d44124dd2612a25f29c2124b836b226bf1b1a4676076",
    "c1efe7276329f5cb4b37063da869fa5668142c29930471ddbdb494dfcc5910ae",
];
const MAP_ROW_SPR_UNCORE: MapfileRow = MapfileRow {
    family_model: "GenuineIntel-6-8F",
    version: "V1.39",
    filename: "/SPR/events/sapphirerapids_uncore.json",
    event_type: PerfmonSourceKind::Uncore,
    source_line: 143,
    source_row_sha256: "12c6ef992e728b643d207505cd07e600a685ab0d5f44263afb471e67e769a728",
};

const MAP_ROW_SPR_UNCORE_EXPERIMENTAL: MapfileRow = MapfileRow {
    family_model: "GenuineIntel-6-8F",
    version: "V1.39",
    filename: "/SPR/events/sapphirerapids_uncore_experimental.json",
    event_type: PerfmonSourceKind::UncoreExperimental,
    source_line: 144,
    source_row_sha256: "381e88051f9e0fd21e85fa15de1ffd14dbaa63ec11d3871995499436cdc0367f",
};

const MAP_ROW_GNR_AD_UNCORE: MapfileRow = MapfileRow {
    family_model: "GenuineIntel-6-AD",
    version: "V1.20",
    filename: "/GNR/events/graniterapids_uncore.json",
    event_type: PerfmonSourceKind::Uncore,
    source_line: 204,
    source_row_sha256: "bedd74545fccf4170c7868b58bc5ad23427b8920fcc1a4e5cac21667aa7e90d4",
};

const MAP_ROW_GNR_AD_UNCORE_EXPERIMENTAL: MapfileRow = MapfileRow {
    family_model: "GenuineIntel-6-AD",
    version: "V1.20",
    filename: "/GNR/events/graniterapids_uncore_experimental.json",
    event_type: PerfmonSourceKind::UncoreExperimental,
    source_line: 205,
    source_row_sha256: "52f3002af7f416d3a1f8465bbc9345a3ac1d9a4586a35f8add1a058a541f7ab3",
};

const MAP_ROW_GNR_AE_UNCORE: MapfileRow = MapfileRow {
    family_model: "GenuineIntel-6-AE",
    version: "V1.20",
    filename: "/GNR/events/graniterapids_uncore.json",
    event_type: PerfmonSourceKind::Uncore,
    source_line: 209,
    source_row_sha256: "79f5bf81b8e33374844e959e5ebd73cbe25cdce1678d3762d10cf2937344e7cb",
};

const MAP_ROW_GNR_AE_UNCORE_EXPERIMENTAL: MapfileRow = MapfileRow {
    family_model: "GenuineIntel-6-AE",
    version: "V1.20",
    filename: "/GNR/events/graniterapids_uncore_experimental.json",
    event_type: PerfmonSourceKind::UncoreExperimental,
    source_line: 210,
    source_row_sha256: "140448054813f7bfbce1009f9fe4f75bd8b77b5ccb544b5481afb7112157a44a",
};

const SPR_UNC_IIO_DATA_REQ_OF_CPU_MEM_READ_ALL_PARTS_COUNTERS: &[ProgrammableCounter] =
    &[ProgrammableCounter::new(0), ProgrammableCounter::new(1)];
const SPR_UNC_IIO_DATA_REQ_OF_CPU_MEM_READ_ALL_PARTS_RUNTIME_FIELDS: &[RuntimeFieldValue] = &[
    RuntimeFieldValue {
        field: RuntimeField::EventCode,
        value: 0x83,
        raw: "0x83",
    },
    RuntimeFieldValue {
        field: RuntimeField::UMask,
        value: 0x4,
        raw: "0x04",
    },
    RuntimeFieldValue {
        field: RuntimeField::PortMask,
        value: 0xff,
        raw: "0x00ff",
    },
    RuntimeFieldValue {
        field: RuntimeField::FCMask,
        value: 0x7,
        raw: "0x07",
    },
];
const SPR_UNC_IIO_DATA_REQ_OF_CPU_MEM_READ_ALL_PARTS_SOURCE_FIELDS: &[SourceField] = &[
    SourceField {
        name: "BriefDescription",
        value: "Read request for 4 bytes made by IIO Part0-7 to Memory",
    },
    SourceField {
        name: "Counter",
        value: "0,1",
    },
    SourceField {
        name: "CounterType",
        value: "PGMABLE",
    },
    SourceField {
        name: "Deprecated",
        value: "0",
    },
    SourceField {
        name: "ELLC",
        value: "0",
    },
    SourceField {
        name: "EventCode",
        value: "0x83",
    },
    SourceField {
        name: "EventName",
        value: "UNC_IIO_DATA_REQ_OF_CPU.MEM_READ.ALL_PARTS",
    },
    SourceField {
        name: "ExtSel",
        value: "0",
    },
    SourceField {
        name: "FCMask",
        value: "0x07",
    },
    SourceField {
        name: "FILTER_VALUE",
        value: "0",
    },
    SourceField {
        name: "Filter",
        value: "na",
    },
    SourceField {
        name: "PortMask",
        value: "0x00ff",
    },
    SourceField {
        name: "PublicDescription",
        value: "Read request for 4 bytes made by IIO Part0-7 to Memory",
    },
    SourceField {
        name: "UMask",
        value: "0x04",
    },
    SourceField {
        name: "UMaskExt",
        value: "0x00000000",
    },
    SourceField {
        name: "Unit",
        value: "IIO",
    },
];
const SPR_UNC_IIO_DATA_REQ_OF_CPU_MEM_READ_ALL_PARTS: PerfmonEvent = PerfmonEvent {
    role: EventRole::IioDataReqOfCpuMemReadAllParts,
    unit: PerfmonUnit::Iio,
    brief_description: "Read request for 4 bytes made by IIO Part0-7 to Memory",
    public_description: "Read request for 4 bytes made by IIO Part0-7 to Memory",
    counter: CounterRestriction {
        raw: "0,1",
        counters: SPR_UNC_IIO_DATA_REQ_OF_CPU_MEM_READ_ALL_PARTS_COUNTERS,
    },
    runtime_fields: SPR_UNC_IIO_DATA_REQ_OF_CPU_MEM_READ_ALL_PARTS_RUNTIME_FIELDS,
    source_fields: SPR_UNC_IIO_DATA_REQ_OF_CPU_MEM_READ_ALL_PARTS_SOURCE_FIELDS,
    provenance: EventProvenance::Direct {
        source_path: "SPR/events/sapphirerapids_uncore.json",
        source_event_name: "UNC_IIO_DATA_REQ_OF_CPU.MEM_READ.ALL_PARTS",
        source_record_sha256: "0312481a7d14b49fe9b2b8a05b14ad5c2ce86ff0f52ce8a0b0123018d29d1e62",
    },
};

const SPR_UNC_IIO_DATA_REQ_OF_CPU_MEM_WRITE_ALL_PARTS_COUNTERS: &[ProgrammableCounter] =
    &[ProgrammableCounter::new(0), ProgrammableCounter::new(1)];
const SPR_UNC_IIO_DATA_REQ_OF_CPU_MEM_WRITE_ALL_PARTS_RUNTIME_FIELDS: &[RuntimeFieldValue] = &[
    RuntimeFieldValue {
        field: RuntimeField::EventCode,
        value: 0x83,
        raw: "0x83",
    },
    RuntimeFieldValue {
        field: RuntimeField::UMask,
        value: 0x1,
        raw: "0x01",
    },
    RuntimeFieldValue {
        field: RuntimeField::PortMask,
        value: 0xff,
        raw: "0x00ff",
    },
    RuntimeFieldValue {
        field: RuntimeField::FCMask,
        value: 0x7,
        raw: "0x07",
    },
];
const SPR_UNC_IIO_DATA_REQ_OF_CPU_MEM_WRITE_ALL_PARTS_SOURCE_FIELDS: &[SourceField] = &[
    SourceField {
        name: "BriefDescription",
        value: "Write request of 4 bytes made by IIO Part0-7 to Memory",
    },
    SourceField {
        name: "Counter",
        value: "0,1",
    },
    SourceField {
        name: "CounterType",
        value: "PGMABLE",
    },
    SourceField {
        name: "Deprecated",
        value: "0",
    },
    SourceField {
        name: "ELLC",
        value: "0",
    },
    SourceField {
        name: "EventCode",
        value: "0x83",
    },
    SourceField {
        name: "EventName",
        value: "UNC_IIO_DATA_REQ_OF_CPU.MEM_WRITE.ALL_PARTS",
    },
    SourceField {
        name: "ExtSel",
        value: "0",
    },
    SourceField {
        name: "FCMask",
        value: "0x07",
    },
    SourceField {
        name: "FILTER_VALUE",
        value: "0",
    },
    SourceField {
        name: "Filter",
        value: "na",
    },
    SourceField {
        name: "PortMask",
        value: "0x00ff",
    },
    SourceField {
        name: "PublicDescription",
        value: "Write request of 4 bytes made by IIO Part0-7 to Memory",
    },
    SourceField {
        name: "UMask",
        value: "0x01",
    },
    SourceField {
        name: "UMaskExt",
        value: "0x00000000",
    },
    SourceField {
        name: "Unit",
        value: "IIO",
    },
];
const SPR_UNC_IIO_DATA_REQ_OF_CPU_MEM_WRITE_ALL_PARTS: PerfmonEvent = PerfmonEvent {
    role: EventRole::IioDataReqOfCpuMemWriteAllParts,
    unit: PerfmonUnit::Iio,
    brief_description: "Write request of 4 bytes made by IIO Part0-7 to Memory",
    public_description: "Write request of 4 bytes made by IIO Part0-7 to Memory",
    counter: CounterRestriction {
        raw: "0,1",
        counters: SPR_UNC_IIO_DATA_REQ_OF_CPU_MEM_WRITE_ALL_PARTS_COUNTERS,
    },
    runtime_fields: SPR_UNC_IIO_DATA_REQ_OF_CPU_MEM_WRITE_ALL_PARTS_RUNTIME_FIELDS,
    source_fields: SPR_UNC_IIO_DATA_REQ_OF_CPU_MEM_WRITE_ALL_PARTS_SOURCE_FIELDS,
    provenance: EventProvenance::Direct {
        source_path: "SPR/events/sapphirerapids_uncore.json",
        source_event_name: "UNC_IIO_DATA_REQ_OF_CPU.MEM_WRITE.ALL_PARTS",
        source_record_sha256: "b84aee00e2cae567bd5ba66ddccf8fd208650169f9979a7f37017b6a39b543db",
    },
};

const SPR_UNC_UPI_TXL_FLITS_ALL_DATA_COUNTERS: &[ProgrammableCounter] = &[
    ProgrammableCounter::new(0),
    ProgrammableCounter::new(1),
    ProgrammableCounter::new(2),
    ProgrammableCounter::new(3),
];
const SPR_UNC_UPI_TXL_FLITS_ALL_DATA_RUNTIME_FIELDS: &[RuntimeFieldValue] = &[
    RuntimeFieldValue {
        field: RuntimeField::EventCode,
        value: 0x2,
        raw: "0x02",
    },
    RuntimeFieldValue {
        field: RuntimeField::UMask,
        value: 0xf,
        raw: "0x0f",
    },
    RuntimeFieldValue {
        field: RuntimeField::PortMask,
        value: 0x0,
        raw: "0x00",
    },
    RuntimeFieldValue {
        field: RuntimeField::FCMask,
        value: 0x0,
        raw: "0x00",
    },
];
const SPR_UNC_UPI_TXL_FLITS_ALL_DATA_SOURCE_FIELDS: &[SourceField] = &[
    SourceField {
        name: "BriefDescription",
        value: "Valid Flits Sent : All Data",
    },
    SourceField {
        name: "Counter",
        value: "0,1,2,3",
    },
    SourceField {
        name: "CounterType",
        value: "PGMABLE",
    },
    SourceField {
        name: "Deprecated",
        value: "0",
    },
    SourceField {
        name: "ELLC",
        value: "0",
    },
    SourceField {
        name: "EventCode",
        value: "0x02",
    },
    SourceField {
        name: "EventName",
        value: "UNC_UPI_TxL_FLITS.ALL_DATA",
    },
    SourceField {
        name: "ExtSel",
        value: "0",
    },
    SourceField {
        name: "FCMask",
        value: "0x00",
    },
    SourceField {
        name: "FILTER_VALUE",
        value: "0",
    },
    SourceField {
        name: "Filter",
        value: "na",
    },
    SourceField {
        name: "PortMask",
        value: "0x00",
    },
    SourceField {
        name: "PublicDescription",
        value: "Valid Flits Sent : All Data : Counts number of data flits across this UPI link.",
    },
    SourceField {
        name: "UMask",
        value: "0x0f",
    },
    SourceField {
        name: "UMaskExt",
        value: "0x00000000",
    },
    SourceField {
        name: "Unit",
        value: "UPI LL",
    },
];
const SPR_UNC_UPI_TXL_FLITS_ALL_DATA: PerfmonEvent = PerfmonEvent {
    role: EventRole::UpiTxDataFlitsAll,
    unit: PerfmonUnit::UpiLl,
    brief_description: "Valid Flits Sent : All Data",
    public_description: "Valid Flits Sent : All Data : Counts number of data flits across this UPI link.",
    counter: CounterRestriction {
        raw: "0,1,2,3",
        counters: SPR_UNC_UPI_TXL_FLITS_ALL_DATA_COUNTERS,
    },
    runtime_fields: SPR_UNC_UPI_TXL_FLITS_ALL_DATA_RUNTIME_FIELDS,
    source_fields: SPR_UNC_UPI_TXL_FLITS_ALL_DATA_SOURCE_FIELDS,
    provenance: EventProvenance::Direct {
        source_path: "SPR/events/sapphirerapids_uncore.json",
        source_event_name: "UNC_UPI_TxL_FLITS.ALL_DATA",
        source_record_sha256: "e8c531d21e175554ae21e730414eddd126deed3b6c2b537edd43c116f44d7e5e",
    },
};

const SPR_UNC_UPI_RXL_FLITS_ALL_DATA_COUNTERS: &[ProgrammableCounter] = &[
    ProgrammableCounter::new(0),
    ProgrammableCounter::new(1),
    ProgrammableCounter::new(2),
    ProgrammableCounter::new(3),
];
const SPR_UNC_UPI_RXL_FLITS_ALL_DATA_RUNTIME_FIELDS: &[RuntimeFieldValue] = &[
    RuntimeFieldValue {
        field: RuntimeField::EventCode,
        value: 0x3,
        raw: "0x03",
    },
    RuntimeFieldValue {
        field: RuntimeField::UMask,
        value: 0xf,
        raw: "0x0f",
    },
    RuntimeFieldValue {
        field: RuntimeField::PortMask,
        value: 0x0,
        raw: "0x00",
    },
    RuntimeFieldValue {
        field: RuntimeField::FCMask,
        value: 0x0,
        raw: "0x00",
    },
];
const SPR_UNC_UPI_RXL_FLITS_ALL_DATA_SOURCE_FIELDS: &[SourceField] = &[
    SourceField {
        name: "BriefDescription",
        value: "Valid Flits Received : All Data",
    },
    SourceField {
        name: "Counter",
        value: "0,1,2,3",
    },
    SourceField {
        name: "CounterType",
        value: "PGMABLE",
    },
    SourceField {
        name: "Deprecated",
        value: "0",
    },
    SourceField {
        name: "ELLC",
        value: "0",
    },
    SourceField {
        name: "EventCode",
        value: "0x03",
    },
    SourceField {
        name: "EventName",
        value: "UNC_UPI_RxL_FLITS.ALL_DATA",
    },
    SourceField {
        name: "ExtSel",
        value: "0",
    },
    SourceField {
        name: "FCMask",
        value: "0x00",
    },
    SourceField {
        name: "FILTER_VALUE",
        value: "0",
    },
    SourceField {
        name: "Filter",
        value: "na",
    },
    SourceField {
        name: "PortMask",
        value: "0x00",
    },
    SourceField {
        name: "PublicDescription",
        value: "Valid Flits Received : All Data : Shows legal flit time (hides impact of L0p and L0c).",
    },
    SourceField {
        name: "UMask",
        value: "0x0f",
    },
    SourceField {
        name: "UMaskExt",
        value: "0x00000000",
    },
    SourceField {
        name: "Unit",
        value: "UPI LL",
    },
];
const SPR_UNC_UPI_RXL_FLITS_ALL_DATA: PerfmonEvent = PerfmonEvent {
    role: EventRole::UpiRxDataFlitsAll,
    unit: PerfmonUnit::UpiLl,
    brief_description: "Valid Flits Received : All Data",
    public_description: "Valid Flits Received : All Data : Shows legal flit time (hides impact of L0p and L0c).",
    counter: CounterRestriction {
        raw: "0,1,2,3",
        counters: SPR_UNC_UPI_RXL_FLITS_ALL_DATA_COUNTERS,
    },
    runtime_fields: SPR_UNC_UPI_RXL_FLITS_ALL_DATA_RUNTIME_FIELDS,
    source_fields: SPR_UNC_UPI_RXL_FLITS_ALL_DATA_SOURCE_FIELDS,
    provenance: EventProvenance::Direct {
        source_path: "SPR/events/sapphirerapids_uncore.json",
        source_event_name: "UNC_UPI_RxL_FLITS.ALL_DATA",
        source_record_sha256: "8db3281e861ef898f4f37f5ab716c47786c5c064ccbe8450dc0046ccabb9564c",
    },
};

const GNR_UNC_IIO_DATA_REQ_OF_CPU_MEM_READ_ALL_PARTS_COUNTERS: &[ProgrammableCounter] =
    &[ProgrammableCounter::new(0), ProgrammableCounter::new(1)];
const GNR_UNC_IIO_DATA_REQ_OF_CPU_MEM_READ_ALL_PARTS_RUNTIME_FIELDS: &[RuntimeFieldValue] = &[
    RuntimeFieldValue {
        field: RuntimeField::EventCode,
        value: 0x83,
        raw: "0x83",
    },
    RuntimeFieldValue {
        field: RuntimeField::UMask,
        value: 0x4,
        raw: "0x04",
    },
    RuntimeFieldValue {
        field: RuntimeField::PortMask,
        value: 0xff,
        raw: "0x0FF",
    },
    RuntimeFieldValue {
        field: RuntimeField::FCMask,
        value: 0x7,
        raw: "0x07",
    },
];
const GNR_UNC_IIO_DATA_REQ_OF_CPU_MEM_READ_ALL_PARTS_SOURCE_FIELDS: &[SourceField] = &[
    SourceField {
        name: "BriefDescription",
        value: "Counts once for every 4 bytes read from this card to memory.  This event does include reads to IO.",
    },
    SourceField {
        name: "Counter",
        value: "0,1",
    },
    SourceField {
        name: "CounterType",
        value: "PGMABLE",
    },
    SourceField {
        name: "Deprecated",
        value: "0",
    },
    SourceField {
        name: "ELLC",
        value: "0",
    },
    SourceField {
        name: "EventCode",
        value: "0x83",
    },
    SourceField {
        name: "EventName",
        value: "UNC_IIO_DATA_REQ_OF_CPU.MEM_READ.ALL_PARTS",
    },
    SourceField {
        name: "ExtSel",
        value: "0",
    },
    SourceField {
        name: "FCMask",
        value: "0x07",
    },
    SourceField {
        name: "FILTER_VALUE",
        value: "0",
    },
    SourceField {
        name: "Filter",
        value: "na",
    },
    SourceField {
        name: "PortMask",
        value: "0x0FF",
    },
    SourceField {
        name: "PublicDescription",
        value: "Counts once for every 4 bytes read from this card to memory.  This event does include reads to IO.",
    },
    SourceField {
        name: "UMask",
        value: "0x04",
    },
    SourceField {
        name: "UMaskExt",
        value: "0x00070FF0",
    },
    SourceField {
        name: "Unit",
        value: "IIO",
    },
];
const GNR_UNC_IIO_DATA_REQ_OF_CPU_MEM_READ_ALL_PARTS: PerfmonEvent = PerfmonEvent {
    role: EventRole::IioDataReqOfCpuMemReadAllParts,
    unit: PerfmonUnit::Iio,
    brief_description: "Counts once for every 4 bytes read from this card to memory.  This event does include reads to IO.",
    public_description: "Counts once for every 4 bytes read from this card to memory.  This event does include reads to IO.",
    counter: CounterRestriction {
        raw: "0,1",
        counters: GNR_UNC_IIO_DATA_REQ_OF_CPU_MEM_READ_ALL_PARTS_COUNTERS,
    },
    runtime_fields: GNR_UNC_IIO_DATA_REQ_OF_CPU_MEM_READ_ALL_PARTS_RUNTIME_FIELDS,
    source_fields: GNR_UNC_IIO_DATA_REQ_OF_CPU_MEM_READ_ALL_PARTS_SOURCE_FIELDS,
    provenance: EventProvenance::Direct {
        source_path: "GNR/events/graniterapids_uncore.json",
        source_event_name: "UNC_IIO_DATA_REQ_OF_CPU.MEM_READ.ALL_PARTS",
        source_record_sha256: "454d96ab91d507db188521cf087187f140129d572c83e5f48bb9aa5808dd3536",
    },
};

const GNR_UNC_IIO_DATA_REQ_OF_CPU_MEM_WRITE_ALL_PARTS_COUNTERS: &[ProgrammableCounter] =
    &[ProgrammableCounter::new(0), ProgrammableCounter::new(1)];
const GNR_UNC_IIO_DATA_REQ_OF_CPU_MEM_WRITE_ALL_PARTS_RUNTIME_FIELDS: &[RuntimeFieldValue] = &[
    RuntimeFieldValue {
        field: RuntimeField::EventCode,
        value: 0x83,
        raw: "0x83",
    },
    RuntimeFieldValue {
        field: RuntimeField::UMask,
        value: 0x1,
        raw: "0x01",
    },
    RuntimeFieldValue {
        field: RuntimeField::PortMask,
        value: 0xff,
        raw: "0x0FF",
    },
    RuntimeFieldValue {
        field: RuntimeField::FCMask,
        value: 0x7,
        raw: "0x07",
    },
];
const GNR_UNC_IIO_DATA_REQ_OF_CPU_MEM_WRITE_ALL_PARTS_SOURCE_FIELDS: &[SourceField] = &[
    SourceField {
        name: "BriefDescription",
        value: "Counts once for every 4 bytes written from this card to memory.  This event does include writes to IO.",
    },
    SourceField {
        name: "Counter",
        value: "0,1",
    },
    SourceField {
        name: "CounterType",
        value: "PGMABLE",
    },
    SourceField {
        name: "Deprecated",
        value: "0",
    },
    SourceField {
        name: "ELLC",
        value: "0",
    },
    SourceField {
        name: "EventCode",
        value: "0x83",
    },
    SourceField {
        name: "EventName",
        value: "UNC_IIO_DATA_REQ_OF_CPU.MEM_WRITE.ALL_PARTS",
    },
    SourceField {
        name: "ExtSel",
        value: "0",
    },
    SourceField {
        name: "FCMask",
        value: "0x07",
    },
    SourceField {
        name: "FILTER_VALUE",
        value: "0",
    },
    SourceField {
        name: "Filter",
        value: "na",
    },
    SourceField {
        name: "PortMask",
        value: "0x0FF",
    },
    SourceField {
        name: "PublicDescription",
        value: "Counts once for every 4 bytes written from this card to memory.  This event does include writes to IO.",
    },
    SourceField {
        name: "UMask",
        value: "0x01",
    },
    SourceField {
        name: "UMaskExt",
        value: "0x00070FF0",
    },
    SourceField {
        name: "Unit",
        value: "IIO",
    },
];
const GNR_UNC_IIO_DATA_REQ_OF_CPU_MEM_WRITE_ALL_PARTS: PerfmonEvent = PerfmonEvent {
    role: EventRole::IioDataReqOfCpuMemWriteAllParts,
    unit: PerfmonUnit::Iio,
    brief_description: "Counts once for every 4 bytes written from this card to memory.  This event does include writes to IO.",
    public_description: "Counts once for every 4 bytes written from this card to memory.  This event does include writes to IO.",
    counter: CounterRestriction {
        raw: "0,1",
        counters: GNR_UNC_IIO_DATA_REQ_OF_CPU_MEM_WRITE_ALL_PARTS_COUNTERS,
    },
    runtime_fields: GNR_UNC_IIO_DATA_REQ_OF_CPU_MEM_WRITE_ALL_PARTS_RUNTIME_FIELDS,
    source_fields: GNR_UNC_IIO_DATA_REQ_OF_CPU_MEM_WRITE_ALL_PARTS_SOURCE_FIELDS,
    provenance: EventProvenance::Direct {
        source_path: "GNR/events/graniterapids_uncore.json",
        source_event_name: "UNC_IIO_DATA_REQ_OF_CPU.MEM_WRITE.ALL_PARTS",
        source_record_sha256: "701ae12bb19fbd1491bd62e171daa9994d1c18c106a10c45bc2e1754527faf5e",
    },
};

const GNR_UNC_UPI_TXL_FLITS_ALL_DATA_COUNTERS: &[ProgrammableCounter] = &[
    ProgrammableCounter::new(0),
    ProgrammableCounter::new(1),
    ProgrammableCounter::new(2),
    ProgrammableCounter::new(3),
];
const GNR_UNC_UPI_TXL_FLITS_ALL_DATA_RUNTIME_FIELDS: &[RuntimeFieldValue] = &[
    RuntimeFieldValue {
        field: RuntimeField::EventCode,
        value: 0x2,
        raw: "0x02",
    },
    RuntimeFieldValue {
        field: RuntimeField::UMask,
        value: 0xf,
        raw: "0x0F",
    },
    RuntimeFieldValue {
        field: RuntimeField::PortMask,
        value: 0x0,
        raw: "0x00",
    },
    RuntimeFieldValue {
        field: RuntimeField::FCMask,
        value: 0x0,
        raw: "0x00",
    },
];
const GNR_UNC_UPI_TXL_FLITS_ALL_DATA_SOURCE_FIELDS: &[SourceField] = &[
    SourceField {
        name: "BriefDescription",
        value: "Valid Flits Sent : All Data : Counts number of data flits across this UPI link.",
    },
    SourceField {
        name: "Counter",
        value: "0,1,2,3",
    },
    SourceField {
        name: "CounterType",
        value: "PGMABLE",
    },
    SourceField {
        name: "Deprecated",
        value: "0",
    },
    SourceField {
        name: "ELLC",
        value: "0",
    },
    SourceField {
        name: "EventCode",
        value: "0x02",
    },
    SourceField {
        name: "EventName",
        value: "UNC_UPI_TxL_FLITS.ALL_DATA",
    },
    SourceField {
        name: "ExtSel",
        value: "0",
    },
    SourceField {
        name: "FCMask",
        value: "0x00",
    },
    SourceField {
        name: "FILTER_VALUE",
        value: "0",
    },
    SourceField {
        name: "Filter",
        value: "na",
    },
    SourceField {
        name: "PortMask",
        value: "0x00",
    },
    SourceField {
        name: "PublicDescription",
        value: "Valid Flits Sent : All Data",
    },
    SourceField {
        name: "UMask",
        value: "0x0F",
    },
    SourceField {
        name: "UMaskExt",
        value: "0x00000000",
    },
    SourceField {
        name: "Unit",
        value: "UPI LL",
    },
];
const GNR_UNC_UPI_TXL_FLITS_ALL_DATA: PerfmonEvent = PerfmonEvent {
    role: EventRole::UpiTxDataFlitsAll,
    unit: PerfmonUnit::UpiLl,
    brief_description: "Valid Flits Sent : All Data : Counts number of data flits across this UPI link.",
    public_description: "Valid Flits Sent : All Data",
    counter: CounterRestriction {
        raw: "0,1,2,3",
        counters: GNR_UNC_UPI_TXL_FLITS_ALL_DATA_COUNTERS,
    },
    runtime_fields: GNR_UNC_UPI_TXL_FLITS_ALL_DATA_RUNTIME_FIELDS,
    source_fields: GNR_UNC_UPI_TXL_FLITS_ALL_DATA_SOURCE_FIELDS,
    provenance: EventProvenance::Direct {
        source_path: "GNR/events/graniterapids_uncore.json",
        source_event_name: "UNC_UPI_TxL_FLITS.ALL_DATA",
        source_record_sha256: "f2dfdddca642726272ff8bc7657cefbcda5e83d7e28190b17779b761ee0d723a",
    },
};

const GNR_UNC_UPI_RXL_FLITS_ALL_DATA_COUNTERS: &[ProgrammableCounter] = &[
    ProgrammableCounter::new(0),
    ProgrammableCounter::new(1),
    ProgrammableCounter::new(2),
    ProgrammableCounter::new(3),
];
const GNR_UNC_UPI_RXL_FLITS_ALL_DATA_RUNTIME_FIELDS: &[RuntimeFieldValue] = &[
    RuntimeFieldValue {
        field: RuntimeField::EventCode,
        value: 0x3,
        raw: "0x03",
    },
    RuntimeFieldValue {
        field: RuntimeField::UMask,
        value: 0xf,
        raw: "0x0F",
    },
    RuntimeFieldValue {
        field: RuntimeField::PortMask,
        value: 0x0,
        raw: "0x00",
    },
    RuntimeFieldValue {
        field: RuntimeField::FCMask,
        value: 0x0,
        raw: "0x00",
    },
];
const GNR_UNC_UPI_RXL_FLITS_ALL_DATA_SOURCE_FIELDS: &[SourceField] = &[
    SourceField {
        name: "BriefDescription",
        value: "Valid Flits Received : All Data : Shows legal flit time (hides impact of L0p and L0c).",
    },
    SourceField {
        name: "Counter",
        value: "0,1,2,3",
    },
    SourceField {
        name: "CounterType",
        value: "PGMABLE",
    },
    SourceField {
        name: "Deprecated",
        value: "0",
    },
    SourceField {
        name: "ELLC",
        value: "0",
    },
    SourceField {
        name: "EventCode",
        value: "0x03",
    },
    SourceField {
        name: "EventName",
        value: "UNC_UPI_RxL_FLITS.ALL_DATA",
    },
    SourceField {
        name: "ExtSel",
        value: "0",
    },
    SourceField {
        name: "FCMask",
        value: "0x00",
    },
    SourceField {
        name: "FILTER_VALUE",
        value: "0",
    },
    SourceField {
        name: "Filter",
        value: "na",
    },
    SourceField {
        name: "PortMask",
        value: "0x00",
    },
    SourceField {
        name: "PublicDescription",
        value: "Valid Flits Received : All Data",
    },
    SourceField {
        name: "UMask",
        value: "0x0F",
    },
    SourceField {
        name: "UMaskExt",
        value: "0x00000000",
    },
    SourceField {
        name: "Unit",
        value: "UPI LL",
    },
];
const GNR_UNC_UPI_RXL_FLITS_ALL_DATA: PerfmonEvent = PerfmonEvent {
    role: EventRole::UpiRxDataFlitsAll,
    unit: PerfmonUnit::UpiLl,
    brief_description: "Valid Flits Received : All Data : Shows legal flit time (hides impact of L0p and L0c).",
    public_description: "Valid Flits Received : All Data",
    counter: CounterRestriction {
        raw: "0,1,2,3",
        counters: GNR_UNC_UPI_RXL_FLITS_ALL_DATA_COUNTERS,
    },
    runtime_fields: GNR_UNC_UPI_RXL_FLITS_ALL_DATA_RUNTIME_FIELDS,
    source_fields: GNR_UNC_UPI_RXL_FLITS_ALL_DATA_SOURCE_FIELDS,
    provenance: EventProvenance::Direct {
        source_path: "GNR/events/graniterapids_uncore.json",
        source_event_name: "UNC_UPI_RxL_FLITS.ALL_DATA",
        source_record_sha256: "6f88a7fe40ca00635f2527a576be8f44a31113b7f68f12622c9a22f09e8feea7",
    },
};

const GNR_UNC_IIO_DATA_REQ_OF_CPU_PEER_WRITE_ALL_PARTS_COUNTERS: &[ProgrammableCounter] =
    &[ProgrammableCounter::new(0), ProgrammableCounter::new(1)];
const GNR_UNC_IIO_DATA_REQ_OF_CPU_PEER_WRITE_ALL_PARTS_RUNTIME_FIELDS: &[RuntimeFieldValue] = &[
    RuntimeFieldValue {
        field: RuntimeField::EventCode,
        value: 0x83,
        raw: "0x83",
    },
    RuntimeFieldValue {
        field: RuntimeField::UMask,
        value: 0x2,
        raw: "0x02",
    },
    RuntimeFieldValue {
        field: RuntimeField::PortMask,
        value: 0xff,
        raw: "0x0FF",
    },
    RuntimeFieldValue {
        field: RuntimeField::FCMask,
        value: 0x7,
        raw: "0x07",
    },
];
const GNR_UNC_IIO_DATA_REQ_OF_CPU_PEER_WRITE_ALL_PARTS_SOURCE_FIELDS: &[SourceField] = &[
    SourceField {
        name: "BriefDescription",
        value: "Counts once for every 4 bytes written from this card to a peer device's IO space.",
    },
    SourceField {
        name: "Counter",
        value: "0,1",
    },
    SourceField {
        name: "CounterType",
        value: "PGMABLE",
    },
    SourceField {
        name: "Deprecated",
        value: "0",
    },
    SourceField {
        name: "ELLC",
        value: "0",
    },
    SourceField {
        name: "EventCode",
        value: "0x83",
    },
    SourceField {
        name: "EventName",
        value: "UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.ALL_PARTS",
    },
    SourceField {
        name: "ExtSel",
        value: "0",
    },
    SourceField {
        name: "FCMask",
        value: "0x07",
    },
    SourceField {
        name: "FILTER_VALUE",
        value: "0",
    },
    SourceField {
        name: "Filter",
        value: "na",
    },
    SourceField {
        name: "PortMask",
        value: "0x0FF",
    },
    SourceField {
        name: "PublicDescription",
        value: "Counts once for every 4 bytes written from this card to a peer device's IO space.",
    },
    SourceField {
        name: "UMask",
        value: "0x02",
    },
    SourceField {
        name: "UMaskExt",
        value: "0x00070FF0",
    },
    SourceField {
        name: "Unit",
        value: "IIO",
    },
];
const GNR_UNC_IIO_DATA_REQ_OF_CPU_PEER_WRITE_ALL_PARTS: PerfmonEvent = PerfmonEvent {
    role: EventRole::IioDataReqOfCpuPeerWriteAllParts,
    unit: PerfmonUnit::Iio,
    brief_description: "Counts once for every 4 bytes written from this card to a peer device's IO space.",
    public_description: "Counts once for every 4 bytes written from this card to a peer device's IO space.",
    counter: CounterRestriction {
        raw: "0,1",
        counters: GNR_UNC_IIO_DATA_REQ_OF_CPU_PEER_WRITE_ALL_PARTS_COUNTERS,
    },
    runtime_fields: GNR_UNC_IIO_DATA_REQ_OF_CPU_PEER_WRITE_ALL_PARTS_RUNTIME_FIELDS,
    source_fields: GNR_UNC_IIO_DATA_REQ_OF_CPU_PEER_WRITE_ALL_PARTS_SOURCE_FIELDS,
    provenance: EventProvenance::Direct {
        source_path: "GNR/events/graniterapids_uncore_experimental.json",
        source_event_name: "UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.ALL_PARTS",
        source_record_sha256: "2960a18b98cb904612fe1a450f001afd72ef9145fccedbb5e02daa6f660ea57e",
    },
};

const GNR_UNC_IIO_DATA_REQ_BY_CPU_PEER_WRITE_ALL_PARTS_COUNTERS: &[ProgrammableCounter] =
    &[ProgrammableCounter::new(2), ProgrammableCounter::new(3)];
const GNR_UNC_IIO_DATA_REQ_BY_CPU_PEER_WRITE_ALL_PARTS_RUNTIME_FIELDS: &[RuntimeFieldValue] = &[
    RuntimeFieldValue {
        field: RuntimeField::EventCode,
        value: 0xc0,
        raw: "0xC0",
    },
    RuntimeFieldValue {
        field: RuntimeField::UMask,
        value: 0x2,
        raw: "0x02",
    },
    RuntimeFieldValue {
        field: RuntimeField::PortMask,
        value: 0xff,
        raw: "0x0FF",
    },
    RuntimeFieldValue {
        field: RuntimeField::FCMask,
        value: 0x7,
        raw: "0x07",
    },
];
const GNR_UNC_IIO_DATA_REQ_BY_CPU_PEER_WRITE_ALL_PARTS_SOURCE_FIELDS: &[SourceField] = &[
    SourceField {
        name: "BriefDescription",
        value: "Data requested by the CPU : Another card (different IIO stack) writing to this card.",
    },
    SourceField {
        name: "Counter",
        value: "2,3",
    },
    SourceField {
        name: "CounterType",
        value: "PGMABLE",
    },
    SourceField {
        name: "Deprecated",
        value: "0",
    },
    SourceField {
        name: "ELLC",
        value: "0",
    },
    SourceField {
        name: "EventCode",
        value: "0xC0",
    },
    SourceField {
        name: "EventName",
        value: "UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.ALL_PARTS",
    },
    SourceField {
        name: "ExtSel",
        value: "0",
    },
    SourceField {
        name: "FCMask",
        value: "0x07",
    },
    SourceField {
        name: "FILTER_VALUE",
        value: "0",
    },
    SourceField {
        name: "Filter",
        value: "na",
    },
    SourceField {
        name: "PortMask",
        value: "0x0FF",
    },
    SourceField {
        name: "PublicDescription",
        value: "Data requested by the CPU : Another card (different IIO stack) writing to this card.",
    },
    SourceField {
        name: "UMask",
        value: "0x02",
    },
    SourceField {
        name: "UMaskExt",
        value: "0x00070FF0",
    },
    SourceField {
        name: "Unit",
        value: "IIO",
    },
];
const GNR_UNC_IIO_DATA_REQ_BY_CPU_PEER_WRITE_ALL_PARTS: PerfmonEvent = PerfmonEvent {
    role: EventRole::IioDataReqByCpuPeerWriteAllParts,
    unit: PerfmonUnit::Iio,
    brief_description: "Data requested by the CPU : Another card (different IIO stack) writing to this card.",
    public_description: "Data requested by the CPU : Another card (different IIO stack) writing to this card.",
    counter: CounterRestriction {
        raw: "2,3",
        counters: GNR_UNC_IIO_DATA_REQ_BY_CPU_PEER_WRITE_ALL_PARTS_COUNTERS,
    },
    runtime_fields: GNR_UNC_IIO_DATA_REQ_BY_CPU_PEER_WRITE_ALL_PARTS_RUNTIME_FIELDS,
    source_fields: GNR_UNC_IIO_DATA_REQ_BY_CPU_PEER_WRITE_ALL_PARTS_SOURCE_FIELDS,
    provenance: EventProvenance::Direct {
        source_path: "GNR/events/graniterapids_uncore.json",
        source_event_name: "UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.ALL_PARTS",
        source_record_sha256: "3ec45e1d803e391297512082857ca1753a95c34f23ab30f9d2596236519abc46",
    },
};

const GNR_UNC_IIO_DATA_REQ_BY_CPU_PEER_READ_ALL_PARTS_COUNTERS: &[ProgrammableCounter] =
    &[ProgrammableCounter::new(2), ProgrammableCounter::new(3)];
const GNR_UNC_IIO_DATA_REQ_BY_CPU_PEER_READ_ALL_PARTS_RUNTIME_FIELDS: &[RuntimeFieldValue] = &[
    RuntimeFieldValue {
        field: RuntimeField::EventCode,
        value: 0xc0,
        raw: "0xC0",
    },
    RuntimeFieldValue {
        field: RuntimeField::UMask,
        value: 0x8,
        raw: "0x08",
    },
    RuntimeFieldValue {
        field: RuntimeField::PortMask,
        value: 0xff,
        raw: "0x0FF",
    },
    RuntimeFieldValue {
        field: RuntimeField::FCMask,
        value: 0x7,
        raw: "0x07",
    },
];
const GNR_UNC_IIO_DATA_REQ_BY_CPU_PEER_READ_ALL_PARTS_SOURCE_FIELDS: &[SourceField] = &[
    SourceField {
        name: "BriefDescription",
        value: "Data requested by the CPU : Another card (different IIO stack) reading from this card.",
    },
    SourceField {
        name: "Counter",
        value: "2,3",
    },
    SourceField {
        name: "CounterType",
        value: "PGMABLE",
    },
    SourceField {
        name: "Deprecated",
        value: "0",
    },
    SourceField {
        name: "ELLC",
        value: "0",
    },
    SourceField {
        name: "EventCode",
        value: "0xC0",
    },
    SourceField {
        name: "EventName",
        value: "UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.ALL_PARTS",
    },
    SourceField {
        name: "ExtSel",
        value: "0",
    },
    SourceField {
        name: "FCMask",
        value: "0x07",
    },
    SourceField {
        name: "FILTER_VALUE",
        value: "0",
    },
    SourceField {
        name: "Filter",
        value: "na",
    },
    SourceField {
        name: "PortMask",
        value: "0x0FF",
    },
    SourceField {
        name: "PublicDescription",
        value: "Data requested by the CPU : Another card (different IIO stack) reading from this card.",
    },
    SourceField {
        name: "UMask",
        value: "0x08",
    },
    SourceField {
        name: "UMaskExt",
        value: "0x00070FF0",
    },
    SourceField {
        name: "Unit",
        value: "IIO",
    },
];
const GNR_UNC_IIO_DATA_REQ_BY_CPU_PEER_READ_ALL_PARTS: PerfmonEvent = PerfmonEvent {
    role: EventRole::IioDataReqByCpuPeerReadAllParts,
    unit: PerfmonUnit::Iio,
    brief_description: "Data requested by the CPU : Another card (different IIO stack) reading from this card.",
    public_description: "Data requested by the CPU : Another card (different IIO stack) reading from this card.",
    counter: CounterRestriction {
        raw: "2,3",
        counters: GNR_UNC_IIO_DATA_REQ_BY_CPU_PEER_READ_ALL_PARTS_COUNTERS,
    },
    runtime_fields: GNR_UNC_IIO_DATA_REQ_BY_CPU_PEER_READ_ALL_PARTS_RUNTIME_FIELDS,
    source_fields: GNR_UNC_IIO_DATA_REQ_BY_CPU_PEER_READ_ALL_PARTS_SOURCE_FIELDS,
    provenance: EventProvenance::Direct {
        source_path: "GNR/events/graniterapids_uncore.json",
        source_event_name: "UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.ALL_PARTS",
        source_record_sha256: "576afd76bd46e127f87ec8dd22cb81807408c381f78c42517c0b3f2dc13c071c",
    },
};

const SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_OF_CPU_PEER_WRITE_ALL_PARTS_COUNTERS:
    &[ProgrammableCounter] = &[ProgrammableCounter::new(0), ProgrammableCounter::new(1)];
const SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_OF_CPU_PEER_WRITE_ALL_PARTS_RUNTIME_FIELDS:
    &[RuntimeFieldValue] = &[
    RuntimeFieldValue {
        field: RuntimeField::EventCode,
        value: 0x83,
        raw: "0x83",
    },
    RuntimeFieldValue {
        field: RuntimeField::UMask,
        value: 0x2,
        raw: "0x02",
    },
    RuntimeFieldValue {
        field: RuntimeField::PortMask,
        value: 0xff,
        raw: "0x00ff",
    },
    RuntimeFieldValue {
        field: RuntimeField::FCMask,
        value: 0x7,
        raw: "0x07",
    },
];
const SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_OF_CPU_PEER_WRITE_ALL_PARTS_SOURCE_FIELDS: &[SourceField] =
    &[
        SourceField {
            name: "BriefDescription",
            value: "Derived union of UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.PART0..UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.PART7",
        },
        SourceField {
            name: "Counter",
            value: "0,1",
        },
        SourceField {
            name: "CounterType",
            value: "PGMABLE",
        },
        SourceField {
            name: "Deprecated",
            value: "0",
        },
        SourceField {
            name: "ELLC",
            value: "0",
        },
        SourceField {
            name: "EventCode",
            value: "0x83",
        },
        SourceField {
            name: "EventName",
            value: "DERIVED_UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.ALL_PARTS",
        },
        SourceField {
            name: "ExtSel",
            value: "0",
        },
        SourceField {
            name: "FCMask",
            value: "0x07",
        },
        SourceField {
            name: "FILTER_VALUE",
            value: "0",
        },
        SourceField {
            name: "Filter",
            value: "na",
        },
        SourceField {
            name: "PortMask",
            value: "0x00ff",
        },
        SourceField {
            name: "PublicDescription",
            value: "Derived by verifying shared non-mask encoding/counter fields across eight source part records, then OR-ing PortMask and validating redundant UMaskExt.",
        },
        SourceField {
            name: "UMask",
            value: "0x02",
        },
        SourceField {
            name: "UMaskExt",
            value: "0x00000000",
        },
        SourceField {
            name: "Unit",
            value: "IIO",
        },
    ];
const SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_OF_CPU_PEER_WRITE_ALL_PARTS: PerfmonEvent = PerfmonEvent {
    role: EventRole::IioDataReqOfCpuPeerWriteAllParts,
    unit: PerfmonUnit::Iio,
    brief_description: "Derived union of UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.PART0..UNC_IIO_DATA_REQ_OF_CPU.PEER_WRITE.PART7",
    public_description: "Derived by verifying shared non-mask encoding/counter fields across eight source part records, then OR-ing PortMask and validating redundant UMaskExt.",
    counter: CounterRestriction {
        raw: "0,1",
        counters: SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_OF_CPU_PEER_WRITE_ALL_PARTS_COUNTERS,
    },
    runtime_fields: SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_OF_CPU_PEER_WRITE_ALL_PARTS_RUNTIME_FIELDS,
    source_fields: SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_OF_CPU_PEER_WRITE_ALL_PARTS_SOURCE_FIELDS,
    provenance: EventProvenance::DerivedUnion {
        source_path: "SPR/events/sapphirerapids_uncore_experimental.json",
        source_event_names: SPR_SPR_UNC_IIO_DATA_REQ_OF_CPU_PEER_WRITE_ALL_PARTS_SOURCE_NAMES,
        source_record_sha256: SPR_SPR_UNC_IIO_DATA_REQ_OF_CPU_PEER_WRITE_ALL_PARTS_SOURCE_HASHES,
        rule: "verified shared non-mask encoding/counter fields across PART0..PART7; OR PortMask; validate redundant UMaskExt",
    },
};

const SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_WRITE_ALL_PARTS_COUNTERS:
    &[ProgrammableCounter] = &[ProgrammableCounter::new(2), ProgrammableCounter::new(3)];
const SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_WRITE_ALL_PARTS_RUNTIME_FIELDS:
    &[RuntimeFieldValue] = &[
    RuntimeFieldValue {
        field: RuntimeField::EventCode,
        value: 0xc0,
        raw: "0xc0",
    },
    RuntimeFieldValue {
        field: RuntimeField::UMask,
        value: 0x2,
        raw: "0x02",
    },
    RuntimeFieldValue {
        field: RuntimeField::PortMask,
        value: 0xff,
        raw: "0x00ff",
    },
    RuntimeFieldValue {
        field: RuntimeField::FCMask,
        value: 0x7,
        raw: "0x07",
    },
];
const SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_WRITE_ALL_PARTS_SOURCE_FIELDS: &[SourceField] =
    &[
        SourceField {
            name: "BriefDescription",
            value: "Derived union of UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.PART0..UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.PART7",
        },
        SourceField {
            name: "Counter",
            value: "2,3",
        },
        SourceField {
            name: "CounterType",
            value: "PGMABLE",
        },
        SourceField {
            name: "Deprecated",
            value: "0",
        },
        SourceField {
            name: "ELLC",
            value: "0",
        },
        SourceField {
            name: "EventCode",
            value: "0xc0",
        },
        SourceField {
            name: "EventName",
            value: "DERIVED_UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.ALL_PARTS",
        },
        SourceField {
            name: "ExtSel",
            value: "0",
        },
        SourceField {
            name: "FCMask",
            value: "0x07",
        },
        SourceField {
            name: "FILTER_VALUE",
            value: "0",
        },
        SourceField {
            name: "Filter",
            value: "na",
        },
        SourceField {
            name: "PortMask",
            value: "0x00ff",
        },
        SourceField {
            name: "PublicDescription",
            value: "Derived by verifying shared non-mask encoding/counter fields across eight source part records, then OR-ing PortMask and validating redundant UMaskExt.",
        },
        SourceField {
            name: "UMask",
            value: "0x02",
        },
        SourceField {
            name: "UMaskExt",
            value: "0x00070FF0",
        },
        SourceField {
            name: "Unit",
            value: "IIO",
        },
    ];
const SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_WRITE_ALL_PARTS: PerfmonEvent = PerfmonEvent {
    role: EventRole::IioDataReqByCpuPeerWriteAllParts,
    unit: PerfmonUnit::Iio,
    brief_description: "Derived union of UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.PART0..UNC_IIO_DATA_REQ_BY_CPU.PEER_WRITE.PART7",
    public_description: "Derived by verifying shared non-mask encoding/counter fields across eight source part records, then OR-ing PortMask and validating redundant UMaskExt.",
    counter: CounterRestriction {
        raw: "2,3",
        counters: SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_WRITE_ALL_PARTS_COUNTERS,
    },
    runtime_fields: SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_WRITE_ALL_PARTS_RUNTIME_FIELDS,
    source_fields: SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_WRITE_ALL_PARTS_SOURCE_FIELDS,
    provenance: EventProvenance::DerivedUnion {
        source_path: "SPR/events/sapphirerapids_uncore_experimental.json",
        source_event_names: SPR_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_WRITE_ALL_PARTS_SOURCE_NAMES,
        source_record_sha256: SPR_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_WRITE_ALL_PARTS_SOURCE_HASHES,
        rule: "verified shared non-mask encoding/counter fields across PART0..PART7; OR PortMask; validate redundant UMaskExt",
    },
};

const SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_READ_ALL_PARTS_COUNTERS:
    &[ProgrammableCounter] = &[ProgrammableCounter::new(2), ProgrammableCounter::new(3)];
const SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_READ_ALL_PARTS_RUNTIME_FIELDS:
    &[RuntimeFieldValue] = &[
    RuntimeFieldValue {
        field: RuntimeField::EventCode,
        value: 0xc0,
        raw: "0xc0",
    },
    RuntimeFieldValue {
        field: RuntimeField::UMask,
        value: 0x8,
        raw: "0x08",
    },
    RuntimeFieldValue {
        field: RuntimeField::PortMask,
        value: 0xff,
        raw: "0x00ff",
    },
    RuntimeFieldValue {
        field: RuntimeField::FCMask,
        value: 0x7,
        raw: "0x07",
    },
];
const SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_READ_ALL_PARTS_SOURCE_FIELDS: &[SourceField] = &[
    SourceField {
        name: "BriefDescription",
        value: "Derived union of UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.PART0..UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.PART7",
    },
    SourceField {
        name: "Counter",
        value: "2,3",
    },
    SourceField {
        name: "CounterType",
        value: "PGMABLE",
    },
    SourceField {
        name: "Deprecated",
        value: "0",
    },
    SourceField {
        name: "ELLC",
        value: "0",
    },
    SourceField {
        name: "EventCode",
        value: "0xc0",
    },
    SourceField {
        name: "EventName",
        value: "DERIVED_UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.ALL_PARTS",
    },
    SourceField {
        name: "ExtSel",
        value: "0",
    },
    SourceField {
        name: "FCMask",
        value: "0x07",
    },
    SourceField {
        name: "FILTER_VALUE",
        value: "0",
    },
    SourceField {
        name: "Filter",
        value: "na",
    },
    SourceField {
        name: "PortMask",
        value: "0x00ff",
    },
    SourceField {
        name: "PublicDescription",
        value: "Derived by verifying shared non-mask encoding/counter fields across eight source part records, then OR-ing PortMask and validating redundant UMaskExt.",
    },
    SourceField {
        name: "UMask",
        value: "0x08",
    },
    SourceField {
        name: "UMaskExt",
        value: "0x00070FF0",
    },
    SourceField {
        name: "Unit",
        value: "IIO",
    },
];
const SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_READ_ALL_PARTS: PerfmonEvent = PerfmonEvent {
    role: EventRole::IioDataReqByCpuPeerReadAllParts,
    unit: PerfmonUnit::Iio,
    brief_description: "Derived union of UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.PART0..UNC_IIO_DATA_REQ_BY_CPU.PEER_READ.PART7",
    public_description: "Derived by verifying shared non-mask encoding/counter fields across eight source part records, then OR-ing PortMask and validating redundant UMaskExt.",
    counter: CounterRestriction {
        raw: "2,3",
        counters: SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_READ_ALL_PARTS_COUNTERS,
    },
    runtime_fields: SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_READ_ALL_PARTS_RUNTIME_FIELDS,
    source_fields: SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_READ_ALL_PARTS_SOURCE_FIELDS,
    provenance: EventProvenance::DerivedUnion {
        source_path: "SPR/events/sapphirerapids_uncore_experimental.json",
        source_event_names: SPR_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_READ_ALL_PARTS_SOURCE_NAMES,
        source_record_sha256: SPR_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_READ_ALL_PARTS_SOURCE_HASHES,
        rule: "verified shared non-mask encoding/counter fields across PART0..PART7; OR PortMask; validate redundant UMaskExt",
    },
};

const GNR_DERIVED_GNR_UNC_IIO_DATA_REQ_OF_CPU_PEER_READ_ALL_PARTS_COUNTERS:
    &[ProgrammableCounter] = &[ProgrammableCounter::new(0), ProgrammableCounter::new(1)];
const GNR_DERIVED_GNR_UNC_IIO_DATA_REQ_OF_CPU_PEER_READ_ALL_PARTS_RUNTIME_FIELDS:
    &[RuntimeFieldValue] = &[
    RuntimeFieldValue {
        field: RuntimeField::EventCode,
        value: 0x83,
        raw: "0x83",
    },
    RuntimeFieldValue {
        field: RuntimeField::UMask,
        value: 0x8,
        raw: "0x08",
    },
    RuntimeFieldValue {
        field: RuntimeField::PortMask,
        value: 0xff,
        raw: "0x00ff",
    },
    RuntimeFieldValue {
        field: RuntimeField::FCMask,
        value: 0x7,
        raw: "0x07",
    },
];
const GNR_DERIVED_GNR_UNC_IIO_DATA_REQ_OF_CPU_PEER_READ_ALL_PARTS_SOURCE_FIELDS: &[SourceField] = &[
    SourceField {
        name: "BriefDescription",
        value: "Derived union of UNC_IIO_DATA_REQ_OF_CPU.PEER_READ.PART0..UNC_IIO_DATA_REQ_OF_CPU.PEER_READ.PART7",
    },
    SourceField {
        name: "Counter",
        value: "0,1",
    },
    SourceField {
        name: "CounterType",
        value: "PGMABLE",
    },
    SourceField {
        name: "Deprecated",
        value: "0",
    },
    SourceField {
        name: "ELLC",
        value: "0",
    },
    SourceField {
        name: "EventCode",
        value: "0x83",
    },
    SourceField {
        name: "EventName",
        value: "DERIVED_UNC_IIO_DATA_REQ_OF_CPU.PEER_READ.ALL_PARTS",
    },
    SourceField {
        name: "ExtSel",
        value: "0",
    },
    SourceField {
        name: "FCMask",
        value: "0x07",
    },
    SourceField {
        name: "FILTER_VALUE",
        value: "0",
    },
    SourceField {
        name: "Filter",
        value: "na",
    },
    SourceField {
        name: "PortMask",
        value: "0x00ff",
    },
    SourceField {
        name: "PublicDescription",
        value: "Derived by verifying shared non-mask encoding/counter fields across eight source part records, then OR-ing PortMask and validating redundant UMaskExt.",
    },
    SourceField {
        name: "UMask",
        value: "0x08",
    },
    SourceField {
        name: "UMaskExt",
        value: "0x00070FF0",
    },
    SourceField {
        name: "Unit",
        value: "IIO",
    },
];
const GNR_DERIVED_GNR_UNC_IIO_DATA_REQ_OF_CPU_PEER_READ_ALL_PARTS: PerfmonEvent = PerfmonEvent {
    role: EventRole::IioDataReqOfCpuPeerReadAllParts,
    unit: PerfmonUnit::Iio,
    brief_description: "Derived union of UNC_IIO_DATA_REQ_OF_CPU.PEER_READ.PART0..UNC_IIO_DATA_REQ_OF_CPU.PEER_READ.PART7",
    public_description: "Derived by verifying shared non-mask encoding/counter fields across eight source part records, then OR-ing PortMask and validating redundant UMaskExt.",
    counter: CounterRestriction {
        raw: "0,1",
        counters: GNR_DERIVED_GNR_UNC_IIO_DATA_REQ_OF_CPU_PEER_READ_ALL_PARTS_COUNTERS,
    },
    runtime_fields: GNR_DERIVED_GNR_UNC_IIO_DATA_REQ_OF_CPU_PEER_READ_ALL_PARTS_RUNTIME_FIELDS,
    source_fields: GNR_DERIVED_GNR_UNC_IIO_DATA_REQ_OF_CPU_PEER_READ_ALL_PARTS_SOURCE_FIELDS,
    provenance: EventProvenance::DerivedUnion {
        source_path: "GNR/events/graniterapids_uncore_experimental.json",
        source_event_names: GNR_GNR_UNC_IIO_DATA_REQ_OF_CPU_PEER_READ_ALL_PARTS_SOURCE_NAMES,
        source_record_sha256: GNR_GNR_UNC_IIO_DATA_REQ_OF_CPU_PEER_READ_ALL_PARTS_SOURCE_HASHES,
        rule: "verified shared non-mask encoding/counter fields across PART0..PART7; OR PortMask; validate redundant UMaskExt",
    },
};

const SPR_EVENTS: &[PerfmonEvent] = &[
    SPR_UNC_IIO_DATA_REQ_OF_CPU_MEM_READ_ALL_PARTS,
    SPR_UNC_IIO_DATA_REQ_OF_CPU_MEM_WRITE_ALL_PARTS,
    SPR_UNC_UPI_TXL_FLITS_ALL_DATA,
    SPR_UNC_UPI_RXL_FLITS_ALL_DATA,
    SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_OF_CPU_PEER_WRITE_ALL_PARTS,
    SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_WRITE_ALL_PARTS,
    SPR_DERIVED_SPR_UNC_IIO_DATA_REQ_BY_CPU_PEER_READ_ALL_PARTS,
];
const GNR_EVENTS: &[PerfmonEvent] = &[
    GNR_UNC_IIO_DATA_REQ_OF_CPU_MEM_READ_ALL_PARTS,
    GNR_UNC_IIO_DATA_REQ_OF_CPU_MEM_WRITE_ALL_PARTS,
    GNR_UNC_UPI_TXL_FLITS_ALL_DATA,
    GNR_UNC_UPI_RXL_FLITS_ALL_DATA,
    GNR_UNC_IIO_DATA_REQ_OF_CPU_PEER_WRITE_ALL_PARTS,
    GNR_UNC_IIO_DATA_REQ_BY_CPU_PEER_WRITE_ALL_PARTS,
    GNR_UNC_IIO_DATA_REQ_BY_CPU_PEER_READ_ALL_PARTS,
    GNR_DERIVED_GNR_UNC_IIO_DATA_REQ_OF_CPU_PEER_READ_ALL_PARTS,
];
const SPR_CPU_MODELS: &[u16] = &[0x8f];
const GNR_CPU_MODELS: &[u16] = &[0xad, 0xae];
const SPR_MAP_ROWS: &[MapfileRow] = &[MAP_ROW_SPR_UNCORE, MAP_ROW_SPR_UNCORE_EXPERIMENTAL];
const GNR_MAP_ROWS: &[MapfileRow] = &[
    MAP_ROW_GNR_AD_UNCORE,
    MAP_ROW_GNR_AD_UNCORE_EXPERIMENTAL,
    MAP_ROW_GNR_AE_UNCORE,
    MAP_ROW_GNR_AE_UNCORE_EXPERIMENTAL,
];
pub const PROFILES: &[PerfmonProfile] = &[
    PerfmonProfile {
        id: PerfmonProfileId::SapphireRapids,
        cpu_models: SPR_CPU_MODELS,
        mapfile_rows: SPR_MAP_ROWS,
        events: SPR_EVENTS,
    },
    PerfmonProfile {
        id: PerfmonProfileId::GraniteRapids,
        cpu_models: GNR_CPU_MODELS,
        mapfile_rows: GNR_MAP_ROWS,
        events: GNR_EVENTS,
    },
];

pub const SOURCES: &[PerfmonSource] = &[
    PerfmonSource {
        path: "SPR/events/sapphirerapids_uncore.json",
        kind: PerfmonSourceKind::Uncore,
        copyright: "Copyright (c) 2001 - 2026 Intel Corporation. All rights reserved.",
        info: "Performance Monitoring Events for 4th Generation Intel(R) Xeon(R) Processor Scalable Family based on Sapphire Rapids microarchitecture - V1.39",
        event_db_version: "1.39",
        date_published: "03/24/2026",
        upstream_sha256: "51eaed4092290ef9275a5b10a4ce9412b319cb19889e7c9ae9853f8b672e8a37",
        selected_event_names: SOURCE_0_EVENT_NAMES,
    },
    PerfmonSource {
        path: "SPR/events/sapphirerapids_uncore_experimental.json",
        kind: PerfmonSourceKind::UncoreExperimental,
        copyright: "Copyright (c) 2001 - 2026 Intel Corporation. All rights reserved.",
        info: "Performance Monitoring Events for 4th Generation Intel(R) Xeon(R) Processor Scalable Family based on Sapphire Rapids microarchitecture - V1.39",
        event_db_version: "1.39",
        date_published: "03/24/2026",
        upstream_sha256: "bf9b826e2bd7e8872d396377e32601dc21191655e465b57cfa16df3f4ce43771",
        selected_event_names: SOURCE_1_EVENT_NAMES,
    },
    PerfmonSource {
        path: "GNR/events/graniterapids_uncore.json",
        kind: PerfmonSourceKind::Uncore,
        copyright: "Copyright (c) 2001 - 2026 Intel Corporation. All rights reserved.",
        info: "Performance Monitoring Events for Intel(R) Xeon(R) 6 Processor with P-cores - V1.20",
        event_db_version: "1.20",
        date_published: "06/05/2026",
        upstream_sha256: "690b0ee0fb6a7c8c5bce8a0d72f3ac8e493c8b5c042e3a650a6ee4174301d513",
        selected_event_names: SOURCE_2_EVENT_NAMES,
    },
    PerfmonSource {
        path: "GNR/events/graniterapids_uncore_experimental.json",
        kind: PerfmonSourceKind::UncoreExperimental,
        copyright: "Copyright (c) 2001 - 2026 Intel Corporation. All rights reserved.",
        info: "Performance Monitoring Events for Intel(R) Xeon(R) 6 Processor with P-cores - V1.20",
        event_db_version: "1.20",
        date_published: "06/05/2026",
        upstream_sha256: "3d8500e8a5a7a8426c79e92f279219119099f288d425545d0f895144285df14f",
        selected_event_names: SOURCE_3_EVENT_NAMES,
    },
];

pub const MAPFILE_ROWS: &[MapfileRow] = &[
    MAP_ROW_SPR_UNCORE,
    MAP_ROW_SPR_UNCORE_EXPERIMENTAL,
    MAP_ROW_GNR_AD_UNCORE,
    MAP_ROW_GNR_AD_UNCORE_EXPERIMENTAL,
    MAP_ROW_GNR_AE_UNCORE,
    MAP_ROW_GNR_AE_UNCORE_EXPERIMENTAL,
];
